### ISSUE TITLE
이슈 등록 연습(Team19)

### ISSUE THREAD

**Issue by megymj** [Jindae/se-practice#5]
이슈 등록 연습입니다.

PR이 합쳐진 커밋은 https://github.com/Jindae/se-practice/commit/875b0679c5548be53563624aedfb6b069847a200 입니다.

**Comment by Yeobeom** [comment]
@bangga0403이 이슈 코멘트 등록 연습입니다.
PR은 다음과 같고 https://github.com/Jindae/se-practice/pull/10 
https://github.com/Jindae/se-practice/pull/10/commits/77a51718641caed5d9e24866d7c10cd341c3669c 마지막 commit입니다.
